### ISSUE TITLE
must include `zip` package for consul puppet module to work right

### ISSUE THREAD

**Issue by benschw** [benschw/vault-demo#2]

**Comment by gartho** [comment]
I've just ran into this issue.  I'm not sure how to fix - I'm just trying to run your demo.

**Comment by gtinjr** [comment]
The consul puppet module is using the unzip command from the guest os that does not have it installed. To get this to work create a bootstrap.sh file in the same location as the VagrantFile with the following contents:

#!/usr/bin/env bash

apt-get update
apt-get install -y unzip

After this file is created edit your VagrantFile and add the following line after config.vm.box = ...:
config.vm.provision :shell, path: "bootstrap.sh"

**Comment by benschw** [comment]
Cool, thanks.
